# Generated by Django 6.0.4 on 2026-07-09 15:48

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books'), ('home', 'Home & Garden'), ('toys', 'Toys & Games'), ('food', 'Food & Beverages'), ('beauty', 'Beauty & Personal Care'), ('sports', 'Sports & Outdoors'), ('automotive', 'Automotive'), ('other', 'Other')], default='other', max_length=50, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books'), ('home', 'Home & Garden'), ('toys', 'Toys & Games'), ('food', 'Food & Beverages'), ('other', 'Other')], default='other', max_length=50, null=True)),
                ('thumbnail', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=255)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'core_product',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=500)),
                ('sku', models.CharField(max_length=500, unique=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'db_table': 'core_product_variant',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('image_type', models.CharField(choices=[('HERO', 'Hero'), ('DETAIL', 'Detail'), ('THUMBNAIL', 'Thumbnail'), ('GALLERY', 'Gallery'), ('SIZE', 'Size Guide'), ('COLOR', 'Color Swatch'), ('LIFESTYLE', 'Lifestyle'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], default='HERO', max_length=20)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant')),
            ],
            options={
                'db_table': 'product_image',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
