# Generated by Django 6.0.4 on 2026-07-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
    ]
