# Generated by Django 6.0.4 on 2026-06-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='product_category',
        ),
    ]
