# Generated by Django 6.0.4 on 2026-07-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productvariant_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='low_stock_threshold',
        ),
    ]
