# Generated by Django 6.0.4 on 2026-07-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variantnumber',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
