# Generated by Django 6.0.4 on 2026-07-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('stationery', 'Papelería y Suministros'), ('books_manuals', 'Libros y Manuales'), ('medical_lab', 'Medicina y Laboratorio'), ('architecture_arts', 'Arquitectura y Artes'), ('electronics', 'Electrónica y Calculadoras'), ('uniforms', 'Uniformes e Institucional'), ('snacks_beverages', 'Snacks y Bebidas')], db_index=True, default='stationery', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Físico'), ('digital', 'Digital'), ('service', 'Servicio')], default='physical', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
