# Generated by Django 6.0.4 on 2026-07-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
