# Generated by Django 6.0.4 on 2026-08-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productvariant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='attribute',
            field=models.CharField(blank=True, default='', help_text="The distinguishing attribute of this variant, e.g. 'Rojo', '4 Pulgadas', 'Talla M'.", max_length=255),
        ),
    ]
