# Generated by Django 6.0.4 on 2026-08-02 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvariant_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.PositiveIntegerField(default=0)),
                ('image_banner', models.URLField(blank=True, default='', max_length=1000)),
                ('image_cart', models.URLField(blank=True, default='', max_length=1000)),
                ('image_default', models.URLField(blank=True, default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'core_category',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category'),
        ),
    ]
