# Generated by Django 6.0.4 on 2026-07-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100013_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='slug',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
