# Generated by Django 6.0.4 on 2026-06-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100000_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.18, max_digits=5),
        ),
    ]
