# Generated by Django 6.0.4 on 2026-07-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100006_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_image_type_per_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metric_unit',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
