# Generated by Django 6.0.4 on 2026-07-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100002_producttype_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('HERO', 'Hero'), ('ORIGINAL', 'Original'), ('SCALE', 'Scale'), ('PACKING', 'Packing'), ('FLATLAY', 'Flatlay'), ('FREEZE_FRAME', 'Freeze Frame')], max_length=20),
        ),
    ]
