# Generated by Django 6.0.4 on 2026-07-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100008_remove_product_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Override price for this variant. If null, use parent product price.', max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this number')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive variants won't be shown to customers")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'core_product_variant',
                'indexes': [models.Index(fields=['sku'], name='core_produc_sku_451f11_idx'), models.Index(fields=['product', 'is_active'], name='core_produc_product_6b62cb_idx'), models.Index(fields=['stock_quantity'], name='core_produc_stock_q_899165_idx')],
            },
        ),
    ]
