# Generated by Django 6.0.4 on 2026-07-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100011_remove_productvariant_core_produc_stock_q_899165_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='core_produc_sku_451f11_idx',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
    ]
