# Generated by Django 6.0.4 on 2026-07-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100010_remove_productvariant_core_produc_product_6b62cb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='core_produc_stock_q_899165_idx',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
    ]
