# Generated by Django 6.0.4 on 2026-06-22 03:18

from django.db import migrations
from django.utils.text import slugify

CATEGORIES = [
    {
        "name": "Electronics",
        "description": "Discover the latest in consumer electronics, from smartphones to smart home devices.",
        "image": "https://images-na.ssl-images-amazon.com/images/G/01/electronics/category/electronics.jpg",
    },
    {
        "name": "Computers",
        "description": "Shop laptops, desktops, monitors, and computer accessories.",
        "image": "https://images-na.ssl-images-amazon.com/images/G/01/computers/category/computers.jpg",
    },
    {
        "name": "Books",
        "description": "Explore millions of books, eBooks, audiobooks, and more.",
        "image": "https://images-na.ssl-images-amazon.com/images/G/01/books/category/books.jpg",
    },
    {
        "name": "Clothing",
        "description": "Fashion for men, women, and kids — from casual to formal.",
        "image": "https://images-na.ssl-images-amazon.com/images/G/01/clothing/category/clothing.jpg",
    },
    {
        "name": "Home & Kitchen",
        "description": "Everything for your home: furniture, appliances, décor, and kitchen essentials.",
        "image": "https://images-na.ssl-images-amazon.com/images/G/01/home/category/home.jpg",
    },
    {
        "name": "Sports & Outdoors",
        "description": "Gear up for every sport and outdoor adventure.",
        "image": "https://images-na.ssl-images-amazon.com/images/G/01/sports/category/sports.jpg",
    },
    {
        "name": "Toys & Games",
        "description": "Find the perfect toy or game for kids of all ages.",
        "image": "https://images-na.ssl-images-amazon.com/images/G/01/toys/category/toys.jpg",
    },
    {
        "name": "Health & Beauty",
        "description": "Personal care, vitamins, supplements, and wellness products.",
        "image": "https://images-na.ssl-images-amazon.com/images/G/01/health/category/health.jpg",
    },
    {
        "name": "Automotive",
        "description": "Car accessories, tools, parts, and maintenance products.",
        "image": "https://images-na.ssl-images-amazon.com/images/G/01/automotive/category/automotive.jpg",
    },
    {
        "name": "Garden & Outdoor",
        "description": "Plants, tools, furniture, and supplies for your garden and patio.",
        "image": "https://images-na.ssl-images-amazon.com/images/G/01/garden/category/garden.jpg",
    },
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("products", "Category")
    for cat in CATEGORIES:
        Category.objects.get_or_create(
            slug=slugify(cat["name"]),
            defaults={
                "name": cat["name"],
                "description": cat["description"],
                "image": cat["image"],
                "status": True,
            },
        )


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("products", "Category")
    slugs = [slugify(cat["name"]) for cat in CATEGORIES]
    Category.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_product_image_alter_productimage_image"),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
