# Generated by Django 6.0.4 on 2026-07-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100005_producttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
