# Generated by Django 6.0.4 on 2026-07-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100012_remove_productvariant_core_produc_sku_451f11_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
