# Generated by Django 6.0.4 on 2026-07-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100007_remove_productimage_unique_image_type_per_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax_rate',
        ),
    ]
