# Generated by Django 6.0.4 on 2026-07-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100004_productimage_image_large_productimage_image_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
