# Generated by Django 6.0.4 on 2026-07-08 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100009_productvariant'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='core_produc_product_6b62cb_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='product_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productvariant'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
    ]
