# Generated by Django 6.0.4 on 2026-07-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '100003_alter_productimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_large',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_medium',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_small',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
