# Generated by Django 6.0.4 on 2026-07-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('image', models.URLField(help_text='URL of the carousel image', max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('button_text', models.CharField(help_text='Text displayed on the button', max_length=50)),
                ('button_link', models.CharField(help_text='URL the button links to', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which slides appear')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this slide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'ordering': ['order', 'id'],
            },
        ),
    ]
