# Generated by Django 6.0.4 on 2026-06-22 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('added_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'payment_provider',
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('reference_document', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('tax', models.FloatField()),
                ('payment_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.paymentprovider')),
            ],
            options={
                'db_table': 'payment_provider_transactions',
            },
        ),
    ]
