# Generated by Django 6.0.4 on 2026-06-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentprovider_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
