# Generated by Django 6.0.4 on 2026-07-06 03:26

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('synopsis', models.TextField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.18, max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.author')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000)),
                ('image_type', models.CharField(choices=[('FRONT_COVER', 'Front Cover'), ('BACK_COVER', 'Back Cover')], max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book')),
            ],
            options={
                'db_table': 'book_image',
                'constraints': [models.UniqueConstraint(fields=('book', 'image_type'), name='unique_image_type_per_book')],
            },
        ),
    ]
