# Generated by Django 6.0.4 on 2026-07-06 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_isbn_alter_book_purchase_cost_and_more'),
        ('products', '100001_product_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='products.product'),
            preserve_default=False,
        ),
    ]
