# Generated by Django 6.0.4 on 2026-07-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='purchase_cost',
        ),
        migrations.RemoveField(
            model_name='book',
            name='selling_price',
        ),
    ]
