# Generated by Django 6.0.4 on 2026-06-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_model',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='employee_model',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
