# Generated by Django 6.0.4 on 2026-07-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution_member',
            field=models.BooleanField(default=False),
        ),
    ]
