# Generated by Django 6.0.4 on 2026-06-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_model_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_model',
            table='core_customer',
        ),
        migrations.AlterModelTable(
            name='employee_model',
            table='core_employee',
        ),
        migrations.AlterModelTable(
            name='user',
            table='core_user',
        ),
    ]
