# Generated by Django 6.0.4 on 2026-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_institution_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True),
        ),
    ]
