# Generated by Django 6.0.4 on 2026-06-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('movement_type', models.CharField(choices=[('initial_inventory', 'Initial Inventory'), ('purchase_entry', 'Purchase Entry'), ('customer_sell', 'Customer Sell')], max_length=50)),
                ('document_reference', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'stock_movement',
            },
        ),
    ]
