# Generated by Django 6.0.4 on 2026-06-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockmovement_model',
            table='core_stock_movement',
        ),
    ]
