# Generated by Django 6.0.4 on 2026-08-03 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockentry_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement_model',
            name='movement_type',
            field=models.CharField(choices=[('initial_inventory', 'Initial Inventory'), ('purchase_entry', 'Purchase Entry'), ('customer_sell', 'Customer Sell'), ('manual_decrease', 'Manual Decrease')], max_length=50),
        ),
        migrations.CreateModel(
            name='StockDecrease_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('decreased_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_decreases', to=settings.AUTH_USER_MODEL)),
                ('stock_movement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_decrease', to='inventory.stockmovement_model')),
            ],
            options={
                'db_table': 'core_stock_decrease',
            },
        ),
    ]
