# Generated by Django 6.0.4 on 2026-08-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockmovement_model_movement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement_model',
            name='movement_type',
            field=models.CharField(choices=[('initial_inventory', 'Initial Inventory'), ('purchase_entry', 'Purchase Entry'), ('customer_sell', 'Customer Sell'), ('manual_decrease', 'Manual Decrease'), ('order_cancelled', 'Order Cancelled')], max_length=50),
        ),
    ]
