# Generated by Django 6.0.4 on 2026-08-08 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('row_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_report_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
