# Generated by Django 6.0.4 on 2026-08-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportlog',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
