# Generated by Django 6.0.4 on 2026-07-08 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '100009_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('sku', models.CharField(max_length=500)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseproduct', to='products.productvariant')),
            ],
            options={
                'db_table': 'productbase',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_type', models.CharField(choices=[('HERO', 'Hero'), ('PACKAGE', 'Package'), ('LIFESTYLE', 'Lifestyle'), ('DETAIL', 'Detail')], max_length=20)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products_base.baseproduct')),
            ],
            options={
                'db_table': 'product_base_image',
                'ordering': ['image_type'],
            },
        ),
    ]
