# Generated by Django 6.0.4 on 2026-04-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='employee_model',
        ),
        migrations.CreateModel(
            name='StockMovement_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('movement_type', models.CharField(choices=[('initial_inventory', 'Initial Inventory'), ('purchase_entry', 'Purchase Entry'), ('customer_sell', 'Customer Sell')], max_length=50)),
                ('document_reference', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
