# Generated by Django 6.0.4 on 2026-04-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_employee_employee_model_stockmovement_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
