# Generated by Django 6.0.4 on 2026-04-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stockpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metric_unit',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('PAIR', 'Shoe pair'), ('BOX', 'Box')], default='UNIT', max_length=10),
        ),
        migrations.DeleteModel(
            name='StockPurchase',
        ),
    ]
