# Generated by Django 6.0.4 on 2026-04-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_metric_unit_delete_stockpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='metric_unit',
        ),
    ]
