# Generated by Django 6.0.4 on 2026-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_stockentry_metric_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement_model',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
