# Generated by Django 6.0.4 on 2026-07-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_status_remove_book_tags_and_more'),
        ('products', '100009_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='product',
        ),
        migrations.AddField(
            model_name='book',
            name='product_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='products.productvariant'),
            preserve_default=False,
        ),
    ]
