# Generated by Django 6.0.4 on 2026-07-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_product_book_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
