# Generated by Django 6.0.4 on 2026-07-09 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_genre_slug'),
        ('books', '009_custom_populate_genred'),
    ]

    operations = [
    ]
