# Generated by Django 6.0.4 on 2026-07-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_merge_0008_genre_slug_009_custom_populate_genred'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
