# Generated by Django 6.0.4 on 2026-07-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('payment', '0003_paymentprovider_is_default'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_payments', to='payment.paymentprovider'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment_provider_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_payments', to='payment.paymentprovidertransaction'),
        ),
    ]
