# Generated by Django 6.0.4 on 2026-06-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
