# Generated by Django 6.0.4 on 2026-08-06 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.CreateModel(
            name='OrderCodeView_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_views', to='orders.order')),
                ('viewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_code_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_order_code_view',
            },
        ),
    ]
