# Generated by Django 6.0.4 on 2026-08-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_pickup_code_ordercodeview_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('returned', 'Returned'), ('payment_failed', 'Payment failed')], default='awaiting_payment', max_length=20),
        ),
    ]
