# Generated by Django 6.0.4 on 2026-06-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='core_product_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='core_product',
        ),
    ]
