# Generated by Django 6.0.4 on 2026-06-10 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_table_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=800)),
                ('image_type', models.CharField(choices=[('HERO', 'Hero'), ('SCALE', 'Scale'), ('PACKING', 'Packing'), ('FLATLAY', 'Flatlay'), ('FREEZE_FRAME', 'Freeze Frame')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'image_type'), name='unique_image_type_per_product')],
            },
        ),
    ]
