# Generated by Django 6.0.4 on 2026-06-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
